### ISSUE TITLE
BackPack 4 support

### ISSUE THREAD

**Issue by Mutahhar** [eduardoarandah/UserManager#7]
Will this package support backpack 4 versions?

**Comment by eduardoarandah** [comment]
Hi! Haven’t got the time to check. 
Would you mind checking if everything works? 
And if you got the time, making a pull request?

**Comment by eletec** [comment]
I try to install on a fresh backPack (4.0) : I get this error message

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for eduardoarandah/usermanager ^1.0 -> satisfiable by eduardoarandah/usermanager[1.0.0, 1.0.x-dev].
    - Can only install one of: backpack/crud[3.6.x-dev, 4.0.22].
    - Can only install one of: backpack/crud[4.0.22, 3.6.x-dev].
    - Can only install one of: backpack/crud[3.6.x-dev, 4.0.22].
    - Conclusion: install backpack/crud 3.6.x-dev
    - Installation request for backpack/crud (locked at 4.0.22, required as 4.0.*) -> satisfiable by backpack/crud[4.0.22].


Installation failed, reverting ./composer.json to its original content.

Is there a fix ?

Thanks

**Comment by eduardoarandah** [comment]
hi!

I've been super busy, haven't had time to check support for backpack v4

If you have the time, can you check if it works? 
Download source code and make composer check for the local path . 

https://fetzi.dev/developing-composer-packages-locally/

if so, I can bump version to support v4

**Comment by tabacitu** [comment]
@eduardoarandah I've added Backpack v4 support to your package. Take a look at PR #8 

Works just like it did before:
![2019-12-03 17 54 40](https://user-images.githubusercontent.com/1032474/70066883-1b288580-15f6-11ea-837d-bdf4eae8d94a.gif)


For future reference:

---

## How to install a Laravel package locally, to make changes

This is how you can install a Laravel package like UserManager on your local disk (instead of using Packagist) to edit it then submit a PR. Even if the package cannot be installed because of dependency conflicts:

1. Fork the repo using Github's button.

2. Clone your fork inside a Laravel installation:
```
git clone git@github.com:tabacitu/UserManager.git packages/usermanager
```

3. Add the service provider to your ```config/app.php``` file:
```
        EduardoArandaH\UserManager\UserManagerServiceProvider::class,
```

4. Add the local requirement to your ```composer.json``` file:
```diff
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
-            "App\\": "app/"
+            "App\\": "app/",
+            "EduardoArandaH\\UserManager\\": "packages/usermanager/src"
        }
    },
```

5. Run ```composer dump-autoload```

This will make your Laravel installation run the package from _your computer_, using a git repo that is linked to _your fork_. When you're done making changes you can:
```
cd packages/usermanager
git commit -am "changes"
git push origin master
# this will have pushed your changes online, on your fork
# now you can go to your fork on Github, and use interface to start a new Pull Request to the original repo 
```

It's more complicated than necessary. I know. It's always been a pain in the ass to do. But it's the fastest way I know how.

Hope it helps someone, someday.

**Comment by ziming** [comment]
Nice @tabacitu 

Didn't know of this way, for my own package, I use https://github.com/franzliedke/studio

to help me in developing my package locally instead.
